### ISSUE TITLE
“Truth Publishing” Network Sites

### ISSUE THREAD

**Issue by ciolt** [marktron/fakenews#26]
All of these sites are part of the same network centered on naturalnews.com, a site notorious for spreading political nonsense and real conspiracy theories - with no basis in facts.

All cite "Natural News" as a source or mention "Truth Publishing" in their privacy policy.

```
Superfoods.news
Grocery.news
Ingredients.news
FoodScience.news
Nutrients.news
Pesticides.news
FoodSupply.news
Monsanto.news
Chocolate.news
SupplementsReport.com
NaturalMedicine.news
Cures.news
NaturalHealth.news
WomensHealth.news
NaturalCures.news
Heart.news
Cosmetics.news
Slender.news
BigPharmaNews.com
Statins.news
Oncology.news
Vaccines.news
HealthFreedom.news
Superbugs.news
Opioids.news
Scientific.news
FakeScience.news
Chemistry.news
Preparedness.news
Gender.news
HeavyMetals.news
Abortions.news
CDC.news
PreventCancer.news
Chemicals.news
RealScienceNews.com
ClimateAlarmism.news
Environ.news
ScienceClowns.com
```

**Comment by ciolt** [comment]
There's a whole lot of other sites, including healthranger.com. Many are centered on creating scandalous "news" stories and promoting snake oil supplements.

**Comment by marktron** [comment]
Thanks @ciolt, found as many more as I could from some of the Privacy Policy boilerplate, I'm sure there are plenty more out there though.

**Comment by spirillen** [comment]
To spread a little `hmm`

I was skimming the PR and found `abortions.news` which was added, as abortion tent to give fire in the US i took a skimming of the site.

**_NOTE_** Haven't read any articles in depth, but it look like they are having a political agenda, rather than spreading false news.

And if a political stand and spread of political word should be based on faq's, how come that electrical car pollutes less than petrol or diesel driven cars? and how did trump end up in the little white house?

What I'm trying to say here, is that I have a hinge of this is a political censorship of those with a different mind rather than actually blocking `real` fake news

I suggest that this submission would be looked over again of those who endorse democracy and freedom of speech.

Just my 2cents

**Comment by ciolt** [comment]
@spirillen The site is fake news. Usually sites like these disguise themselves as “conservative” and “pro-free speech”, but they fit the definition of misinforming with false claims.

Articles like “Planned Parenthood paid for prostitutes for its staffers and big donors” is not true. The site is run by Truth Publishing, an ironic name for a company that specializes in deliberately spreading lies.

If you want *REAL* news that's right-leaning/conservative, there's always Fox News, Reason, and others. These aren't fake news, because they report true stories & do not focus on creating scandalous articles for clicks & attention.
